name: json-flatten
version: 0.1.0.0
github: "githubuser/json-flatten"
license: BSD3
author: "Tanmoy Das"
maintainer: "tan@example.com"
copyright: "2023 Tanmoy Das"

extra-source-files:
    - README.md
    - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/json-flatten#readme>

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - bytestring
    - containers
    - unordered-containers
    - text

ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

library:
    source-dirs: src

executables:
    json-flatten-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - json-flatten

tests:
    json-flatten-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - json-flatten
